export type AirportOption = {
  id: string;
  code: string;
  name: string;
  city: string;
  country: string;
  type: "airport" | "city";
  latitude: number;
  longitude: number;
};

export const mockAirports: AirportOption[] = [
  {
    id: "erbil-city",
    code: "EBL-CITY",
    name: "Erbil",
    city: "Erbil",
    country: "Iraq",
    type: "city",
    latitude: 36.1911,
    longitude: 44.0092,
  },
  {
    id: "erbil-airport",
    code: "EBL",
    name: "Erbil International Airport",
    city: "Erbil",
    country: "Iraq",
    type: "airport",
    latitude: 36.2376,
    longitude: 43.9632,
  },
  {
    id: "sulaymaniyah-airport",
    code: "ISU",
    name: "Sulaymaniyah International Airport",
    city: "Sulaymaniyah",
    country: "Iraq",
    type: "airport",
    latitude: 35.5608,
    longitude: 45.3167,
  },
  {
    id: "duhok-city",
    code: "DUH",
    name: "Duhok",
    city: "Duhok",
    country: "Iraq",
    type: "city",
    latitude: 36.8617,
    longitude: 42.9885,
  },
  {
    id: "istanbul-city",
    code: "IST-CITY",
    name: "Istanbul",
    city: "Istanbul",
    country: "Türkiye",
    type: "city",
    latitude: 41.0082,
    longitude: 28.9784,
  },
  {
    id: "istanbul-airport",
    code: "IST",
    name: "Istanbul Airport",
    city: "Istanbul",
    country: "Türkiye",
    type: "airport",
    latitude: 41.2753,
    longitude: 28.7519,
  },
  {
    id: "dubai-city",
    code: "DXB-CITY",
    name: "Dubai",
    city: "Dubai",
    country: "United Arab Emirates",
    type: "city",
    latitude: 25.2048,
    longitude: 55.2708,
  },
  {
    id: "dubai-airport",
    code: "DXB",
    name: "Dubai International Airport",
    city: "Dubai",
    country: "United Arab Emirates",
    type: "airport",
    latitude: 25.2532,
    longitude: 55.3657,
  },
  {
    id: "antalya-city",
    code: "AYT-CITY",
    name: "Antalya",
    city: "Antalya",
    country: "Türkiye",
    type: "city",
    latitude: 36.8969,
    longitude: 30.7133,
  },
  {
    id: "antalya-airport",
    code: "AYT",
    name: "Antalya Airport",
    city: "Antalya",
    country: "Türkiye",
    type: "airport",
    latitude: 36.8987,
    longitude: 30.8005,
  },
  {
    id: "berlin-city",
    code: "BER-CITY",
    name: "Berlin",
    city: "Berlin",
    country: "Germany",
    type: "city",
    latitude: 52.52,
    longitude: 13.405,
  },
  {
    id: "berlin-airport",
    code: "BER",
    name: "Berlin Brandenburg Airport",
    city: "Berlin",
    country: "Germany",
    type: "airport",
    latitude: 52.3667,
    longitude: 13.5033,
  },
  {
    id: "ankara-airport",
    code: "ESB",
    name: "Ankara Esenboga Airport",
    city: "Ankara",
    country: "Türkiye",
    type: "airport",
    latitude: 40.1281,
    longitude: 32.9951,
  },
  {
    id: "london-city",
    code: "LON-CITY",
    name: "London",
    city: "London",
    country: "United Kingdom",
    type: "city",
    latitude: 51.5072,
    longitude: -0.1276,
  },
  {
    id: "heathrow-airport",
    code: "LHR",
    name: "London Heathrow Airport",
    city: "London",
    country: "United Kingdom",
    type: "airport",
    latitude: 51.47,
    longitude: -0.4543,
  },
  {
    id: "gatwick-airport",
    code: "LGW",
    name: "London Gatwick Airport",
    city: "London",
    country: "United Kingdom",
    type: "airport",
    latitude: 51.1537,
    longitude: -0.1821,
  },
  {
    id: "stansted-airport",
    code: "STN",
    name: "London Stansted Airport",
    city: "London",
    country: "United Kingdom",
    type: "airport",
    latitude: 51.886,
    longitude: 0.2389,
  },
];
