export type FlightBadge = "Best" | "Cheapest" | "Fastest" | null;

export type MockFlight = {
  id: string;
  airline: string;
  flightNumber: string;
  origin: string;
  destination: string;
  departureTime: string;
  arrivalTime: string;
  duration: string;
  durationMinutes: number;
  stops: number;
  price: number;
  badge: FlightBadge;
};

export const mockFlights: MockFlight[] = [
  {
    id: "f1",
    airline: "KurdFlight",
    flightNumber: "KF 201",
    origin: "EBL",
    destination: "IST",
    departureTime: "07:25",
    arrivalTime: "10:10",
    duration: "2h 45m",
    durationMinutes: 165,
    stops: 0,
    price: 149,
    badge: "Best",
  },
  {
    id: "f2",
    airline: "Fly Erbil",
    flightNumber: "FE 114",
    origin: "EBL",
    destination: "IST",
    departureTime: "11:50",
    arrivalTime: "14:55",
    duration: "3h 05m",
    durationMinutes: 185,
    stops: 0,
    price: 132,
    badge: "Cheapest",
  },
  {
    id: "f3",
    airline: "Anatolia Air",
    flightNumber: "AA 782",
    origin: "EBL",
    destination: "IST",
    departureTime: "17:40",
    arrivalTime: "20:20",
    duration: "2h 40m",
    durationMinutes: 160,
    stops: 0,
    price: 171,
    badge: "Fastest",
  },
  {
    id: "f4",
    airline: "KurdFlight",
    flightNumber: "KF 322",
    origin: "EBL",
    destination: "DXB",
    departureTime: "08:15",
    arrivalTime: "11:30",
    duration: "3h 15m",
    durationMinutes: 195,
    stops: 0,
    price: 189,
    badge: "Best",
  },
  {
    id: "f5",
    airline: "Gulf Connect",
    flightNumber: "GC 607",
    origin: "EBL",
    destination: "DXB",
    departureTime: "15:10",
    arrivalTime: "19:05",
    duration: "3h 55m",
    durationMinutes: 235,
    stops: 1,
    price: 164,
    badge: "Cheapest",
  },
  {
    id: "f6",
    airline: "KurdFlight",
    flightNumber: "KF 178",
    origin: "ISU",
    destination: "AYT",
    departureTime: "09:05",
    arrivalTime: "12:00",
    duration: "2h 55m",
    durationMinutes: 175,
    stops: 0,
    price: 172,
    badge: "Best",
  },
  {
    id: "f7",
    airline: "Mediterranean Air",
    flightNumber: "MA 443",
    origin: "ISU",
    destination: "AYT",
    departureTime: "18:20",
    arrivalTime: "22:30",
    duration: "4h 10m",
    durationMinutes: 250,
    stops: 1,
    price: 151,
    badge: "Cheapest",
  },
  {
    id: "f8",
    airline: "KurdFlight",
    flightNumber: "KF 511",
    origin: "DUH",
    destination: "BER",
    departureTime: "06:45",
    arrivalTime: "11:40",
    duration: "5h 55m",
    durationMinutes: 355,
    stops: 1,
    price: 265,
    badge: "Best",
  },
  {
    id: "f9",
    airline: "EuroSky",
    flightNumber: "ES 341",
    origin: "DUH",
    destination: "BER",
    departureTime: "13:30",
    arrivalTime: "19:55",
    duration: "6h 25m",
    durationMinutes: 385,
    stops: 1,
    price: 241,
    badge: "Cheapest",
  },
  {
    id: "f10",
    airline: "KurdFlight",
    flightNumber: "KF 233",
    origin: "ISU",
    destination: "IST",
    departureTime: "07:55",
    arrivalTime: "10:55",
    duration: "3h 00m",
    durationMinutes: 180,
    stops: 0,
    price: 146,
    badge: null,
  },
  {
    id: "f11",
    airline: "Sky Mesopotamia",
    flightNumber: "SM 921",
    origin: "ISU",
    destination: "IST",
    departureTime: "16:40",
    arrivalTime: "19:50",
    duration: "3h 10m",
    durationMinutes: 190,
    stops: 0,
    price: 138,
    badge: null,
  },
  {
    id: "f12",
    airline: "KurdFlight",
    flightNumber: "KF 202",
    origin: "IST",
    destination: "EBL",
    departureTime: "13:10",
    arrivalTime: "15:50",
    duration: "2h 40m",
    durationMinutes: 160,
    stops: 0,
    price: 141,
    badge: null,
  },
  {
    id: "f13",
    airline: "Fly Erbil",
    flightNumber: "FE 115",
    origin: "IST",
    destination: "EBL",
    departureTime: "17:05",
    arrivalTime: "20:15",
    duration: "3h 10m",
    durationMinutes: 190,
    stops: 0,
    price: 129,
    badge: null,
  },
  {
    id: "f14",
    airline: "Anatolia Air",
    flightNumber: "AA 783",
    origin: "IST",
    destination: "EBL",
    departureTime: "21:15",
    arrivalTime: "23:55",
    duration: "2h 40m",
    durationMinutes: 160,
    stops: 0,
    price: 166,
    badge: null,
  },
  {
    id: "f15",
    airline: "KurdFlight",
    flightNumber: "KF 323",
    origin: "DXB",
    destination: "EBL",
    departureTime: "14:40",
    arrivalTime: "17:55",
    duration: "3h 15m",
    durationMinutes: 195,
    stops: 0,
    price: 183,
    badge: null,
  },
  {
    id: "f16",
    airline: "Gulf Connect",
    flightNumber: "GC 608",
    origin: "DXB",
    destination: "EBL",
    departureTime: "19:25",
    arrivalTime: "23:20",
    duration: "3h 55m",
    durationMinutes: 235,
    stops: 1,
    price: 159,
    badge: null,
  },
  {
    id: "f17",
    airline: "KurdFlight",
    flightNumber: "KF 179",
    origin: "AYT",
    destination: "ISU",
    departureTime: "13:25",
    arrivalTime: "16:15",
    duration: "2h 50m",
    durationMinutes: 170,
    stops: 0,
    price: 168,
    badge: null,
  },
  {
    id: "f18",
    airline: "Mediterranean Air",
    flightNumber: "MA 444",
    origin: "AYT",
    destination: "ISU",
    departureTime: "22:10",
    arrivalTime: "02:20",
    duration: "4h 10m",
    durationMinutes: 250,
    stops: 1,
    price: 149,
    badge: null,
  },
  {
    id: "f19",
    airline: "KurdFlight",
    flightNumber: "KF 512",
    origin: "BER",
    destination: "DUH",
    departureTime: "14:10",
    arrivalTime: "19:55",
    duration: "5h 45m",
    durationMinutes: 345,
    stops: 1,
    price: 258,
    badge: null,
  },
  {
    id: "f20",
    airline: "EuroSky",
    flightNumber: "ES 342",
    origin: "BER",
    destination: "DUH",
    departureTime: "18:40",
    arrivalTime: "01:05",
    duration: "6h 25m",
    durationMinutes: 385,
    stops: 1,
    price: 236,
    badge: null,
  },
  {
    id: "f21",
    airline: "KurdFlight",
    flightNumber: "KF 234",
    origin: "IST",
    destination: "ISU",
    departureTime: "12:40",
    arrivalTime: "15:35",
    duration: "2h 55m",
    durationMinutes: 175,
    stops: 0,
    price: 142,
    badge: null,
  },
  {
    id: "f22",
    airline: "Sky Mesopotamia",
    flightNumber: "SM 922",
    origin: "IST",
    destination: "ISU",
    departureTime: "20:10",
    arrivalTime: "23:20",
    duration: "3h 10m",
    durationMinutes: 190,
    stops: 0,
    price: 135,
    badge: null,
  },
];
